version: "3.4"

services:
  talentprobeservice:
    image: talentprobeservice
    container_name: talentprobeservice
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo.docker:27017
      ONEAUTH_API: https://api.ioak.io:8010/api
      ONEAUTH_API_KEY: fc2076f5-bee6-4b94-974f-5e110495b048
      ONEAUTH_REALM_ID: 219
      DODO_URL: https://api.ioak.io:8120
      DODO_KEY: e6bacf5e598649e7ab52ce6fca446924
      PORT: 8095
    ports:
      - 8095:8095
    networks:
      ioak-net:
        aliases:
          - talentprobeservice.docker

networks:
  ioak-net:
    external: true
