version: '3.5'
services:
    talentprobeservice:
        container_name: talentprobeservice
        restart: always
        environment:
            MONGODB_DB: talentprobe
            MONGODB_URI: mongodb://mongo.docker:27017
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8125:8125"
        networks:
          ioak-net:
            aliases:
              - talentprobeservice.docker

networks:
  ioak-net:
    external: true
